"""add_default_value_to_event_updated_at

Revision ID: 00ac68bf1bc1
Revises: 3d29129b39d7
Create Date: 2025-10-27 17:04:14.717516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00ac68bf1bc1'
down_revision: Union[str, None] = '3d29129b39d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('eventos', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
