"""Estrutura de dados inicial e validada

Revision ID: 0867e4903a57
Revises: 
Create Date: 2025-10-20 16:42:04.422733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0867e4903a57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_assessorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('contato', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_assessorias_descricao'), 'dim_assessorias', ['descricao'], unique=False)
    op.create_index(op.f('ix_dim_assessorias_id'), 'dim_assessorias', ['id'], unique=False)
    op.create_table('dim_buffets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('contato', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_buffets_descricao'), 'dim_buffets', ['descricao'], unique=False)
    op.create_index(op.f('ix_dim_buffets_id'), 'dim_buffets', ['id'], unique=False)
    op.create_table('dim_cidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_cidades_id'), 'dim_cidades', ['id'], unique=False)
    op.create_index(op.f('ix_dim_cidades_nome'), 'dim_cidades', ['nome'], unique=False)
    op.create_table('dim_clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('contato_principal', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_clientes_email'), 'dim_clientes', ['email'], unique=False)
    op.create_index(op.f('ix_dim_clientes_id'), 'dim_clientes', ['id'], unique=False)
    op.create_index(op.f('ix_dim_clientes_nome'), 'dim_clientes', ['nome'], unique=False)
    op.create_table('dim_insumos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('tipo_insumo', sa.String(), nullable=True),
    sa.Column('unidade_medida', sa.Enum('KG', 'UNIDADE', 'LITRO', name='unidademedida'), nullable=False),
    sa.Column('vlr_referencia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_insumos_descricao'), 'dim_insumos', ['descricao'], unique=False)
    op.create_index(op.f('ix_dim_insumos_id'), 'dim_insumos', ['id'], unique=False)
    op.create_table('dim_locais_evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('capacidade_maxima', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_locais_evento_descricao'), 'dim_locais_evento', ['descricao'], unique=False)
    op.create_index(op.f('ix_dim_locais_evento_id'), 'dim_locais_evento', ['id'], unique=False)
    op.create_table('dim_tipos_evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_tipos_evento_descricao'), 'dim_tipos_evento', ['descricao'], unique=True)
    op.create_index(op.f('ix_dim_tipos_evento_id'), 'dim_tipos_evento', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('nome_completo', sa.String(), nullable=True),
    sa.Column('perfil', sa.Enum('ADMINISTRATIVO', 'OPERACIONAL', name='userprofile'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_nome_completo'), 'usuarios', ['nome_completo'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_evento', sa.Date(), nullable=False),
    sa.Column('horas_festa', sa.Integer(), nullable=True),
    sa.Column('qtde_convidados_prevista', sa.Integer(), nullable=True),
    sa.Column('status_evento', sa.Enum('ORCAMENTO', 'CONFIRMADO', 'REALIZADO', 'CANCELADO', name='eventostatus'), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_local_evento', sa.Integer(), nullable=True),
    sa.Column('id_tipo_evento', sa.Integer(), nullable=True),
    sa.Column('id_cidade', sa.Integer(), nullable=True),
    sa.Column('id_assessoria', sa.Integer(), nullable=True),
    sa.Column('id_buffet', sa.Integer(), nullable=True),
    sa.Column('id_usuario_criador', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_assessoria'], ['dim_assessorias.id'], ),
    sa.ForeignKeyConstraint(['id_buffet'], ['dim_buffets.id'], ),
    sa.ForeignKeyConstraint(['id_cidade'], ['dim_cidades.id'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['dim_clientes.id'], ),
    sa.ForeignKeyConstraint(['id_local_evento'], ['dim_locais_evento.id'], ),
    sa.ForeignKeyConstraint(['id_tipo_evento'], ['dim_tipos_evento.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_criador'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_id'), 'eventos', ['id'], unique=False)
    op.create_table('degustacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_degustacao', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('AGENDADA', 'REALIZADA', 'CANCELADA', name='degustacaostatus'), nullable=False),
    sa.Column('vlr_degustacao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('feedback_cliente', sa.Text(), nullable=True),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('id_usuario_criador', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_criador'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_degustacoes_id'), 'degustacoes', ['id'], unique=False)
    op.create_table('despesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vlr_unitario_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vlr_total_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_despesa', sa.Date(), nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('id_insumo', sa.Integer(), nullable=False),
    sa.Column('id_usuario_criador', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['id_insumo'], ['dim_insumos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_criador'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_despesas_id'), 'despesas', ['id'], unique=False)
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vlr_unitario_por_convidado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vlr_total_contrato', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_venda', sa.Date(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('id_usuario_criador', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_criador'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_evento')
    )
    op.create_index(op.f('ix_vendas_id'), 'vendas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendas_id'), table_name='vendas')
    op.drop_table('vendas')
    op.drop_index(op.f('ix_despesas_id'), table_name='despesas')
    op.drop_table('despesas')
    op.drop_index(op.f('ix_degustacoes_id'), table_name='degustacoes')
    op.drop_table('degustacoes')
    op.drop_index(op.f('ix_eventos_id'), table_name='eventos')
    op.drop_table('eventos')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_nome_completo'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_dim_tipos_evento_id'), table_name='dim_tipos_evento')
    op.drop_index(op.f('ix_dim_tipos_evento_descricao'), table_name='dim_tipos_evento')
    op.drop_table('dim_tipos_evento')
    op.drop_index(op.f('ix_dim_locais_evento_id'), table_name='dim_locais_evento')
    op.drop_index(op.f('ix_dim_locais_evento_descricao'), table_name='dim_locais_evento')
    op.drop_table('dim_locais_evento')
    op.drop_index(op.f('ix_dim_insumos_id'), table_name='dim_insumos')
    op.drop_index(op.f('ix_dim_insumos_descricao'), table_name='dim_insumos')
    op.drop_table('dim_insumos')
    op.drop_index(op.f('ix_dim_clientes_nome'), table_name='dim_clientes')
    op.drop_index(op.f('ix_dim_clientes_id'), table_name='dim_clientes')
    op.drop_index(op.f('ix_dim_clientes_email'), table_name='dim_clientes')
    op.drop_table('dim_clientes')
    op.drop_index(op.f('ix_dim_cidades_nome'), table_name='dim_cidades')
    op.drop_index(op.f('ix_dim_cidades_id'), table_name='dim_cidades')
    op.drop_table('dim_cidades')
    op.drop_index(op.f('ix_dim_buffets_id'), table_name='dim_buffets')
    op.drop_index(op.f('ix_dim_buffets_descricao'), table_name='dim_buffets')
    op.drop_table('dim_buffets')
    op.drop_index(op.f('ix_dim_assessorias_id'), table_name='dim_assessorias')
    op.drop_index(op.f('ix_dim_assessorias_descricao'), table_name='dim_assessorias')
    op.drop_table('dim_assessorias')
    # ### end Alembic commands ###
