"""adicionados_valores_na_coluna_update_at_padrap

Revision ID: 3d29129b39d7
Revises: a97f4d5a8c38
Create Date: 2025-10-27 15:41:02.841089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d29129b39d7'
down_revision: Union[str, None] = 'a97f4d5a8c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
